import FlowFree
from timeit import default_timer as timer

print("5x5 Puzzle - Dumb Backtracking Algorithm")
puzzle = FlowFree.Puzzle('inputs/5x5.txt')
start = timer()
puzzle.btAlgorithm()
end = timer()
print("Assignments: " + str(puzzle.numAssignments))
print("Run Time: " + str(end - start))
print()

print("5x5 Puzzle - Smart Backtracking Algorithm")
puzzle = FlowFree.Puzzle('inputs/5x5.txt')
start = timer()
puzzle.smarterBtAlgorithm()
end = timer()
print("Assignments: " + str(puzzle.numAssignments))
print("Run Time: " + str(end - start))
print()

#print("7x7 Puzzle - Dumb Backtracking Algorithm")
#puzzle = FlowFree.Puzzle('inputs/7x7.txt')
#start = timer()
#puzzle.btAlgorithm()
#end = timer()
#print("Assignments: " + str(puzzle.numAssignments))
#print("Run Time: " + str(end - start))
#print()

print("7x7 Puzzle - Smart Backtracking Algorithm")
puzzle = FlowFree.Puzzle('inputs/7x7.txt')
start = timer()
puzzle.smarterBtAlgorithm()
end = timer()
print("Assignments: " + str(puzzle.numAssignments))
print("Run Time: " + str(end - start))
print()

#print("8x8 Puzzle - Dumb Backtracking Algorithm")
#puzzle = FlowFree.Puzzle('inputs/8x8.txt')
#start = timer()
#puzzle.btAlgorithm()
#end = timer()
#print("Assignments: " + str(puzzle.numAssignments))
#print("Run Time: " + str(end - start))
#print()

print("8x8 Puzzle - Smart Backtracking Algorithm")
puzzle = FlowFree.Puzzle('inputs/8x8.txt')
start = timer()
puzzle.smarterBtAlgorithm()
end = timer()
print("Assignments: " + str(puzzle.numAssignments))
print("Run Time: " + str(end - start))
print()

#print("9x9 Puzzle - Dumb Backtracking Algorithm")
#puzzle = FlowFree.Puzzle('inputs/9x9.txt')
#start = timer()
#puzzle.btAlgorithm()
#end = timer()
#print("Assignments: " + str(puzzle.numAssignments))
#print("Run Time: " + str(end - start))
#print()

print("9x9 Puzzle - Smart Backtracking Algorithm")
puzzle = FlowFree.Puzzle('inputs/9x9.txt')
start = timer()
puzzle.smarterBtAlgorithm()
end = timer()
print("Assignments: " + str(puzzle.numAssignments))
print("Run Time: " + str(end - start))
print()

print("10x10 v1 Puzzle - Smart Backtracking Algorithm")
puzzle = FlowFree.Puzzle('inputs/10x10v1.txt')
start = timer()
puzzle.smarterBtAlgorithm()
end = timer()
print("Assignments: " + str(puzzle.numAssignments))
print("Run Time: " + str(end - start))
print()

print("10x10 v2 Puzzle - Smart Backtracking Algorithm")
puzzle = FlowFree.Puzzle('inputs/10x10v2.txt')
start = timer()
puzzle.smarterBtAlgorithm()
end = timer()
print("Assignments: " + str(puzzle.numAssignments))
print("Run Time: " + str(end - start))
print()

print("12x12 Puzzle - Smart Backtracking Algorithm")
puzzle = FlowFree.Puzzle('inputs/12x12.txt')
start = timer()
puzzle.smarterBtAlgorithm()
end = timer()
print("Assignments: " + str(puzzle.numAssignments))
print("Run Time: " + str(end - start))
print()

print("12x14 Puzzle - Smart Backtracking Algorithm")
puzzle = FlowFree.Puzzle('inputs/12x14.txt')
start = timer()
puzzle.smarterBtAlgorithm()
end = timer()
print("Assignments: " + str(puzzle.numAssignments))
print("Run Time: " + str(end - start))
print()

print("14x14 Puzzle - Smart Backtracking Algorithm")
puzzle = FlowFree.Puzzle('inputs/14x14.txt')
start = timer()
puzzle.smarterBtAlgorithm()
end = timer()
print("Assignments: " + str(puzzle.numAssignments))
print("Run Time: " + str(end - start))
print()
